export const AUTHOR_CREATE = 'AUTHOR_CREATE';
export const AUTHOR_FETCH = 'AUTHOR_FETCH';
export const AUTHOR_DELETE = 'AUTHOR_DELETE';
export const AUTHOR_FAILED = 'AUTHOR_FAILED';
export const AUTHOR_REQUEST = 'AUTHOR_REQUEST';
export const AUTHOR_RESET = 'AUTHOR_RESET';
export const AUTHOR_EDIT = 'AUTHOR_EDIT';
export const AUTHOR_CURRENTPAGE = 'AUTHOR_CURRENTPAGE';

export const GET_AUTHOR_NAMES_REQUEST = 'GET_AUTHOR_NAMES_REQUEST';
export const GET_AUTHOR_NAMES_SUCCESS = 'GET_AUTHOR_NAMES_SUCCESS';
export const GET_AUTHOR_NAMES_FAILED = 'GET_AUTHOR_NAMES_FAILED';
export const GET_AUTHOR_NAMES_RESET = 'GET_AUTHOR_NAMES_RESET';

export const GET_AUTHOR_DETAILS_REQUEST = 'GET_AUTHOR_DETAILS_REQUEST';
export const GET_AUTHOR_DETAILS_SUCCESS = 'GET_AUTHOR_DETAILS_SUCCESS';
export const GET_AUTHOR_DETAILS_FAIL = 'GET_AUTHOR_DETAILS_FAIL';
export const GET_AUTHOR_DETAILS_RESET = 'GET_AUTHOR_DETAILS_RESET';
