export const AUTHOR_CREATE = 'AUTHOR_CREATE';
export const AUTHOR_FETCH = 'AUTHOR_FETCH';
export const AUTHOR_DELETE = 'AUTHOR_DELETE';
export const AUTHOR_FAILED = 'AUTHOR_FAILED';
export const AUTHOR_REQUEST = 'AUTHOR_REQUEST';
export const AUTHOR_RESET = 'AUTHOR_RESET';
export const AUTHOR_EDIT = 'AUTHOR_EDIT';
export const AUTHOR_CURRENTPAGE = 'AUTHOR_CURRENTPAGE';