export const BLOG_CREATE = 'BLOG_CREATE';
export const BLOG_FETCH = 'BLOG_FETCH';
export const BLOG_DELETE = 'BLOG_DELETE';
export const BLOG_FAILED = 'BLOG_FAILED';
export const BLOG_REQUEST = 'BLOG_REQUEST';
export const BLOG_RESET = 'BLOG_RESET';
export const BLOG_EDIT = 'BLOG_EDIT';
export const BLOG_CURRENTPAGE = 'BLOG_CURRENTPAGE';

export const GET_DETAILS_BLOG_REQUEST = 'GET_DETAILS_BLOG_REQUEST';
export const GET_DETAILS_BLOG_SUCCESS = 'GET_DETAILS_BLOG_SUCCESS';
export const GET_DETAILS_BLOG_FAIL = 'GET_DETAILS_BLOG_FAIL';
export const GET_DETAILS_BLOG_RESET = 'GET_DETAILS_BLOG_RESET';