export const BOOK_CREATE = 'BOOK_CREATE';
export const BOOK_FETCH = 'BOOK_FETCH';
export const BOOK_DELETE = 'BOOK_DELETE';
export const BOOK_FAILED = 'BOOK_FAILED';
export const BOOK_REQUEST = 'BOOK_REQUEST';
export const BOOK_RESET = 'BOOK_RESET';
export const BOOK_EDIT = 'BOOK_EDIT';
export const BOOK_SINGLE = 'BOOK_SINGLE';


export const NEWARRIVAL_REQUEST = 'NEWARRIVAL_REQUEST';
export const NEWARRIVAL_SUCCESS = 'NEWARRIVAL_SUCCESS';
export const NEWARRIVAL_FAIL = 'NEWARRIVAL_FAIL';

export const EDITORS_BOOKS_REQUEST = 'EDITORS_BOOKS_REQUEST';
export const EDITORS_BOOKS_SUCCESS = 'EDITORS_BOOKS_SUCCESS';
export const EDITORS_BOOKS_FAIL = 'EDITORS_BOOKS_FAIL';

export const CLASSICS_BOOKS_REQUEST = 'CLASSICS_BOOKS_REQUEST';
export const CLASSICS_BOOKS_SUCCESS = 'CLASSICS_BOOKS_SUCCESS';
export const CLASSICS_BOOKS_FAIL = 'CLASSICS_BOOKS_FAIL';

export const SINGLE_BOOK_REQUEST = 'SINGLE_BOOK_REQUEST';
export const SINGLE_BOOK_SUCCESS = 'SINGLE_BOOK_SUCCESS';
export const SINGLE_BOOK_FAIL = 'SINGLE_BOOK_FAIL';