export const CAROUSAL_CREATE = 'CAROUSAL_CREATE';
export const CAROUSAL_FETCH = 'CAROUSAL_FETCH';
export const CAROUSAL_EDIT = 'CAROUSAL_EDIT';
export const CAROUSAL_DELETE = 'CAROUSAL_DELETE';
export const CAROUSAL_FAILED = 'CAROUSAL_FAILED';
export const CAROUSAL_REQUEST = 'CAROUSAL_REQUEST';
export const CAROUSAL_RESET = 'CAROUSAL_RESET';