export const GENERE_CREATE = 'GENERE_CREATE';
export const GENERE_FETCH = 'GENERE_FETCH';
export const GENERE_DELETE = 'GENERE_DELETE';
export const GENERE_FAILED = 'GENERE_FAILED';
export const GENERE_REQUEST = 'GENERE_REQUEST';
export const GENERE_RESET = 'GENERE_RESET';
export const GENERE_LIST = 'GENERE_LIST';
export const GENERE_CURRENTPAGE = 'GENERE_CURRENTPAGE';