export {default as Login} from './auth/LoginPage';
export {default as Register} from './auth/RegisterPage'
export {default as Home} from './HomePage';
export {default as Dashboard} from './Dashboard'
export {default as AdminDashboard} from './admin/Dashboard';
export {default as BlogDetail} from './blog/BlogDetails';
export {default as Author} from './AuthorPage';
export {default as BookDetails} from './BookDetails';
export {default as Category} from './category/Category';
export {default as CreateBlog} from './admin/CreateBlog';
export {default as AddAuthor} from './admin/AddAuthor';
export {default as AddCarousal} from './admin/AddCarousal';
export {default as Genere} from './admin/Genere';
export {default as AddBooks} from './admin/AddBooks';
export {default as Search} from './search/Search';